### ISSUE TITLE
Spawn broken on current patch

### ISSUE THREAD

**Issue by Bubblegum3390** [ShadowOne333/Metroid-Zero-Mission-Redux#2]
On the current patch dated Sep 6, the first spawn is glitched and starts outside the Plasma Beam room resulting in a softlock. Tested patching with Rom Patcher JS 3.0 and Lunar IPS 1.03. Play tested on Bizhawk 2.9.1's mGBA core and open_agb_firm on 3DS.
![Metroid Zero Mission Redux 2024-10-29 01 00 05](https://github.com/user-attachments/assets/31926da4-17ef-40a8-8f40-809e3b969466)

**Comment by ShadowOne333** [comment]
Oh I'm sorry.
I completely forgot I left in some debugging options I was testing when trying to make the Unknown Items behave as in the original game.

I just changed it back, please try again with the latest patch I just pushed and let me know if it worked.

**Comment by Bubblegum3390** [comment]
Tested the new patch and the game starts correctly thanks!
